name: simil
channels:
  - https://conda.anaconda.org/pytorch
  - https://conda.anaconda.org/nvidia
  - https://conda.anaconda.org/conda-forge
dependencies:
    - python==3.9
    - openslide
    - openslide-python
    - pandas
    - tqdm
    - matplotlib
    - pillow
    - pip
    - pip:
        - opencv-python
        - pandas
        - scikit-image
        - scipy
        - shapely
        - scikit-learn
        - networkx
        - astropy 
        - community
        - multiprocess
        - torch
        - torchvision
        - torchaudio
        - albumentations
        - wandb
